[#759] Add smooth handling for network errors
Problem: When network flag is used with tezos-node
config if url provided is not working, the binary
exits with a nasty error message

Solution: Add a handler that will pretty print the error
message should it occur on a command that uses
--network flag

diff --git a/docker/package/scripts/tezos-node-start b/docker/package/scripts/tezos-node-start
--- a/docker/package/scripts/tezos-node-start
+++ b/docker/package/scripts/tezos-node-start
@@ -26,6 +26,10 @@ if [[ -z "${CUSTOM_NODE_CONFIG:-}" ]]; then
                 ${NETWORK:+"--network=$NETWORK"} \
                 "$@"
     fi
+    if [ $? -eq 124 ]; then
+        echo "Error: provided network config url is incorrect"
+        exit 1
+    fi
     node_run_args=("--config-file" "$config_file")
 else
     echo "Run using custom node config file"
